module.exports = {
  apps: [
    {
      name: 'indian-foods-api',
      script: './server.js',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        UPLOAD_DIR: '/var/www/uploads/',
        UPLOAD_PATH: '/var/www/uploads/',
      },
    },
    {
      name: 'indian-foods-socket',
      script: './socket-server.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        UPLOAD_DIR: '/var/www/uploads/',
        UPLOAD_PATH: '/var/www/uploads/',
      },
    },
    {
      name: 'indian-foods-scheduler',
      script: './scheduler-server.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        UPLOAD_DIR: '/var/www/uploads/',
        UPLOAD_PATH: '/var/www/uploads/',
      },
    },
    {
      name: 'indian-foods-worker-otp',
      script: './src/queues/workers/otp.worker.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: { NODE_ENV: 'production', UPLOAD_DIR: '/var/www/uploads/', UPLOAD_PATH: '/var/www/uploads/' },
    },
    {
      name: 'indian-foods-worker-notification',
      script: './src/queues/workers/notification.worker.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: { NODE_ENV: 'production', UPLOAD_DIR: '/var/www/uploads/', UPLOAD_PATH: '/var/www/uploads/' },
    },
    {
      name: 'indian-foods-worker-order',
      script: './src/queues/workers/order.worker.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: { NODE_ENV: 'production', UPLOAD_DIR: '/var/www/uploads/', UPLOAD_PATH: '/var/www/uploads/' },
    },
    {
      name: 'indian-foods-worker-tracking',
      script: './src/queues/workers/tracking.worker.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: { NODE_ENV: 'production', UPLOAD_DIR: '/var/www/uploads/', UPLOAD_PATH: '/var/www/uploads/' },
    },
    {
      name: 'indian-foods-worker-payment',
      script: './src/queues/workers/payment.worker.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: { NODE_ENV: 'production', UPLOAD_DIR: '/var/www/uploads/', UPLOAD_PATH: '/var/www/uploads/' },
    }
  ],
};
