export const PAYMENT_COLLECTIONS = Object.freeze({
    PAYMENT_RECORDS: 'payment_records',
    PAYMENT_REFUNDS: 'payment_refunds',
    PAYMENT_SETTLEMENTS: 'payment_settlements',
    PAYMENT_TRANSACTIONS: 'payment_transactions',
    PAYMENT_GATEWAY_EVENTS: 'payment_gateway_events',
    PAYMENT_FOOD_TRANSACTIONS: 'payment_food_transactions',
    PAYMENT_ADMIN_WALLETS: 'payment_admin_wallets',
    PAYMENT_DELIVERY_WALLETS: 'payment_delivery_wallets',
    PAYMENT_DELIVERY_WITHDRAWALS: 'payment_delivery_withdrawals',
    PAYMENT_FEE_SETTINGS: 'payment_fee_settings',
    PAYMENT_RESTAURANT_COMMISSIONS: 'payment_restaurant_commissions',
    PAYMENT_RESTAURANT_WALLETS: 'payment_restaurant_wallets',
    PAYMENT_TIFFIN_COMMISSION_SETTINGS: 'payment_tiffin_commission_settings',
    PAYMENT_TIFFIN_PAYOUTS: 'payment_tiffin_payouts',
    PAYMENT_USER_WALLETS: 'payment_user_wallets'
});

export const LEGACY_PAYMENT_COLLECTIONS = Object.freeze({
    PAYMENT_RECORDS: 'payments',
    PAYMENT_REFUNDS: 'refunds',
    PAYMENT_SETTLEMENTS: 'settlements',
    PAYMENT_TRANSACTIONS: 'transactions',
    PAYMENT_GATEWAY_EVENTS: 'processed_gateway_events',
    PAYMENT_FOOD_TRANSACTIONS: 'food_transactions',
    PAYMENT_ADMIN_WALLETS: 'food_admin_wallets',
    PAYMENT_DELIVERY_WALLETS: 'food_delivery_wallets',
    PAYMENT_DELIVERY_WITHDRAWALS: 'food_delivery_withdrawals',
    PAYMENT_FEE_SETTINGS: 'food_fee_settings',
    PAYMENT_RESTAURANT_COMMISSIONS: 'food_restaurant_commissions',
    PAYMENT_RESTAURANT_WALLETS: 'food_restaurant_wallets',
    PAYMENT_TIFFIN_COMMISSION_SETTINGS: 'food_tiffin_commission_settings',
    PAYMENT_TIFFIN_PAYOUTS: 'food_tiffin_payouts',
    PAYMENT_USER_WALLETS: 'food_user_wallets'
});

export const PAYMENT_COLLECTION_RENAMES = Object.freeze([
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_RECORDS,
        to: PAYMENT_COLLECTIONS.PAYMENT_RECORDS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_REFUNDS,
        to: PAYMENT_COLLECTIONS.PAYMENT_REFUNDS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_SETTLEMENTS,
        to: PAYMENT_COLLECTIONS.PAYMENT_SETTLEMENTS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_TRANSACTIONS,
        to: PAYMENT_COLLECTIONS.PAYMENT_TRANSACTIONS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_GATEWAY_EVENTS,
        to: PAYMENT_COLLECTIONS.PAYMENT_GATEWAY_EVENTS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_FOOD_TRANSACTIONS,
        to: PAYMENT_COLLECTIONS.PAYMENT_FOOD_TRANSACTIONS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_ADMIN_WALLETS,
        to: PAYMENT_COLLECTIONS.PAYMENT_ADMIN_WALLETS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_DELIVERY_WALLETS,
        to: PAYMENT_COLLECTIONS.PAYMENT_DELIVERY_WALLETS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_DELIVERY_WITHDRAWALS,
        to: PAYMENT_COLLECTIONS.PAYMENT_DELIVERY_WITHDRAWALS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_FEE_SETTINGS,
        to: PAYMENT_COLLECTIONS.PAYMENT_FEE_SETTINGS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_RESTAURANT_COMMISSIONS,
        to: PAYMENT_COLLECTIONS.PAYMENT_RESTAURANT_COMMISSIONS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_RESTAURANT_WALLETS,
        to: PAYMENT_COLLECTIONS.PAYMENT_RESTAURANT_WALLETS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_TIFFIN_COMMISSION_SETTINGS,
        to: PAYMENT_COLLECTIONS.PAYMENT_TIFFIN_COMMISSION_SETTINGS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_TIFFIN_PAYOUTS,
        to: PAYMENT_COLLECTIONS.PAYMENT_TIFFIN_PAYOUTS
    },
    {
        from: LEGACY_PAYMENT_COLLECTIONS.PAYMENT_USER_WALLETS,
        to: PAYMENT_COLLECTIONS.PAYMENT_USER_WALLETS
    }
]);
